name: dart_audio_graph_miniaudio
description: An extension package for dart_audio_graph using miniaudio.
version: 0.0.1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  dart_audio_graph:
    path: ../dart_audio_graph

dev_dependencies:
  ffigen: ^7.2.4
  lints: ^2.0.0
  test: ^1.16.0

ffigen:
  name: 'MaBridge'
  output: 'lib/generated/ma_bridge_bindings.dart'
  headers:
    entry-points:
      - 'bridge/src/**.h'
