name: dart_audio_graph
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  ffi: ^2.0.1
  disposing: ^1.0.3+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
