name: dart_audio_graph
description: A cross-platform audio processing library written in dart
version: 0.0.1
repository: https://github.com/SKKbySSK/dart_audio_graph/tree/main/packages/dart_audio_graph

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  ffi: ^2.0.1
  disposing: ^1.0.3+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
