name: flutter_audio_graph_miniaudio
description: A new Flutter plugin project.
version: 0.0.1
repository: https://github.com/SKKbySSK/dart_audio_graph/tree/main/packages/flutter_audio_graph_miniaudio

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dart_audio_graph:
    path: ../dart_audio_graph
  dart_audio_graph_miniaudio:
    path: ../dart_audio_graph_miniaudio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_audio_graph_miniaudio
        pluginClass: FlutterAudioGraphMiniaudioPlugin
      ios:
        pluginClass: FlutterAudioGraphMiniaudioPlugin
      macos:
        pluginClass: FlutterAudioGraphMiniaudioPlugin
