name: dart_audio_graph_fft
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/SKKbySSK/dart_audio_graph/tree/main/packages/dart_audio_graph_fft

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  fftea: ^1.2.0+1
  dart_audio_graph:
    path: ../dart_audio_graph

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
