name: audio_graph_demo
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  coast_audio:
    path: ../../packages/coast_audio

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
